/** 
 * Generated by Creer at 03:01PM on November 10, 2015 UTC, git hash: '1b69e788060071d644dd7b8745dca107577844e1'
 * Can put out fires completely.
 */
package games.anarchy;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import org.json.JSONObject;

import joueur.Client;
import joueur.BaseGame;
import joueur.BaseGameObject;
// <<-- Creer-Merge: imports -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
// you can add addtional import(s) here
// <<-- /Creer-Merge: imports -->>
@SuppressWarnings("unused")

/**
 * Can put out fires completely.
 */
public class FireDepartment extends Building {
    /**
     * The amount of fire removed from a building when bribed to extinguish a building.
     */
    public int fireExtinguished;


    // <<-- Creer-Merge: fields -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    // you can add addtional field(s) here. None of them will be tracked or updated by the server.
    // <<-- /Creer-Merge: fields -->>


    /**
     * Creates a new instance of FireDepartment. Used during game initialization, do not call directly.
     */
    public FireDepartment() {
        super();
    }

    /**
     * Bribes this FireDepartment to extinguish the some of the fire in a building.
     *
     * @param   building  The Building you want to extinguish.
     * @return true if the bribe worked, false otherwise
     */
    public boolean extinguish(Building building) {
        JSONObject args = new JSONObject();
        args.put("building", Client.getInstance().gameManager.serializeSafe(building));
        return (boolean)this.runOnServer("extinguish", args);
    }

    // <<-- Creer-Merge: methods -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    // you can add addtional method(s) here.
    // <<-- /Creer-Merge: methods -->>
}
