/** 
 * Generated by Creer at 09:34PM on November 23, 2015 UTC, git hash: '1b69e788060071d644dd7b8745dca107577844e1'
 * A chess piece
 */
package games.chess;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import org.json.JSONObject;

import joueur.Client;
import joueur.BaseGame;
import joueur.BaseGameObject;
// <<-- Creer-Merge: imports -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
// you can add addtional import(s) here
// <<-- /Creer-Merge: imports -->>
@SuppressWarnings("unused")

/**
 * A chess piece
 */
public class Piece extends GameObject {
    /**
     * When the piece has been captured (removed from the board) this is true. Otherwise false.
     */
    public boolean captured;

    /**
     * The file (y) coordinate of the checker.
     */
    public int file;

    /**
     * If the piece has moved from its starting position.
     */
    public boolean hasMoved;

    /**
     * The player that controls this chess Piece.
     */
    public Player owner;

    /**
     * The rank (x) coordinate of the checker, traditionally represented as a letter.
     */
    public int rank;

    /**
     * The type of chess piece this is, either: "King", "Queen", "Knight", "Rook", "Bishop", or "Pawn"
     */
    public String type;


    // <<-- Creer-Merge: fields -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    // you can add addtional field(s) here. None of them will be tracked or updated by the server.
    // <<-- /Creer-Merge: fields -->>


    /**
     * Creates a new instance of Piece. Used during game initialization, do not call directly.
     */
    public Piece() {
        super();
    }

    /**
     * Defaults the value for the optional arg 'promotionType' to '""'
     *
     * @see Piece#move(int, int, String)
     */
    public boolean move(int rank, int file) {
        return this.move(rank, file, "");
    }

    /**
     * Moves the piece from its current location to the given rank and file.
     *
     * @param   rank  The rank (x) coordinate to move to.
     * @param   file  The file (y) coordinate to move to.
     * @param   promotionType  If this is a Pawn moving to the end of the board then this parameter is what to promote it to.
     * @return true if the move was valid, false otherwise
     */
    public boolean move(int rank, int file, String promotionType) {
        JSONObject args = new JSONObject();
        args.put("rank", Client.getInstance().gameManager.serializeSafe(rank));
        args.put("file", Client.getInstance().gameManager.serializeSafe(file));
        args.put("promotionType", Client.getInstance().gameManager.serializeSafe(promotionType));
        return (boolean)this.runOnServer("move", args);
    }

    // <<-- Creer-Merge: methods -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    // you can add addtional method(s) here.
    // <<-- /Creer-Merge: methods -->>
}
