/**
 * Generated by Creer at 12:33AM on March 01, 2016 UTC, git hash: 'f67dd2eb994fc0ce12bba97b92a5c185ebfa7a5d'
 * A player in this game. Every AI controls one player.
 */
package games.chess;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import org.json.JSONObject;
import joueur.Client;
import joueur.BaseGame;
import joueur.BaseGameObject;

// <<-- Creer-Merge: imports -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
// you can add addtional import(s) here
// <<-- /Creer-Merge: imports -->>

/**
 * A player in this game. Every AI controls one player.
 */
public class Player extends GameObject {
    /**
     * What type of client this is, e.g. 'Python', 'JavaScript', or some other language. For potential data mining purposes.
     */
    public String clientType;

    /**
     * The color (side) of this player. Either 'White' or 'Black', with the 'White' player having the first move.
     */
    public String color;

    /**
     * True if this player is currently in check, and must move out of check, false otherwise.
     */
    public boolean inCheck;

    /**
     * If the player lost the game or not.
     */
    public boolean lost;

    /**
     * If the Player has made their move for the turn. true means they can no longer move a Piece this turn.
     */
    public boolean madeMove;

    /**
     * The name of the player.
     */
    public String name;

    /**
     * This player's opponent in the game.
     */
    public Player otherPlayer;

    /**
     * All the unpcaptured chess Pieces owned by this player.
     */
    public List<Piece> pieces;

    /**
     * The direction your Pieces must go along the rank axis until they reach the other side.
     */
    public int rankDirection;

    /**
     * The reason why the player lost the game.
     */
    public String reasonLost;

    /**
     * The reason why the player won the game.
     */
    public String reasonWon;

    /**
     * The amount of time (in ns) remaining for this AI to send commands.
     */
    public float timeRemaining;

    /**
     * If the player won the game or not.
     */
    public boolean won;


    // <<-- Creer-Merge: fields -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    // you can add addtional field(s) here. None of them will be tracked or updated by the server.
    // <<-- /Creer-Merge: fields -->>


    /**
     * Creates a new instance of a Player. Used during game initialization, do not call directly.
     */
    public Player() {
        super();
        this.pieces = new ArrayList<Piece>();
    }

    // <<-- Creer-Merge: methods -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    // you can add addtional method(s) here.
    // <<-- /Creer-Merge: methods -->>
}
