/**
 * Generated by Creer at 04:24PM on March 02, 2016 UTC, git hash: '0cc14891fb0c7c6bec65a23a8e2497e80f8827c1'
 * A Spiderling that creates and spits new Webs from the Nest it is on to another Nest, connecting them.
 */
package games.spiders;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import org.json.JSONObject;
import joueur.Client;
import joueur.BaseGame;
import joueur.BaseGameObject;

// <<-- Creer-Merge: imports -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
// you can add addtional import(s) here
// <<-- /Creer-Merge: imports -->>

/**
 * A Spiderling that creates and spits new Webs from the Nest it is on to another Nest, connecting them.
 */
public class Spitter extends Spiderling {
    /**
     * The Nest that this Spitter is creating a Web to spit at, thus connecting them. Null if not spitting.
     */
    public Nest spittingWebToNest;


    // <<-- Creer-Merge: fields -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    // you can add addtional field(s) here. None of them will be tracked or updated by the server.
    // <<-- /Creer-Merge: fields -->>


    /**
     * Creates a new instance of a Spitter. Used during game initialization, do not call directly.
     */
    public Spitter() {
        super();
    }

    /**
     * Creates and spits a new Web from the Nest the Spitter is on to another Nest, connecting them.
     *
     * @return True if the spit was successful, false otherwise.
     */
    public boolean spit() {
        JSONObject args = new JSONObject();
        return (boolean)this.runOnServer("spit", args);
    }

    // <<-- Creer-Merge: methods -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    // you can add addtional method(s) here.
    // <<-- /Creer-Merge: methods -->>
}
