/**
 * Generated by Creer at 03:34AM on April 07, 2016 UTC, git hash: 'e7ec4e35c89d7556b9e07d4331ac34052ac011bd'
 * A Spiderling that creates and spits new Webs from the Nest it is on to another Nest, connecting them.
 */
package games.spiders;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import org.json.JSONObject;
import joueur.Client;
import joueur.BaseGame;
import joueur.BaseGameObject;

// <<-- Creer-Merge: imports -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
// you can add addtional import(s) here
// <<-- /Creer-Merge: imports -->>

/**
 * A Spiderling that creates and spits new Webs from the Nest it is on to another Nest, connecting them.
 */
public class Spitter extends Spiderling {
    /**
     * The Nest that this Spitter is creating a Web to spit at, thus connecting them. Null if not spitting.
     */
    public Nest spittingWebToNest;


    // <<-- Creer-Merge: fields -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    // you can add addtional field(s) here. None of them will be tracked or updated by the server.
    // <<-- /Creer-Merge: fields -->>


    /**
     * Creates a new instance of a Spitter. Used during game initialization, do not call directly.
     */
    public Spitter() {
        super();
    }

    /**
     * Creates and spits a new Web from the Nest the Spitter is on to another Nest, connecting them.
     *
     * @param   nest  The Nest you want to spit a Web to, thus connecting that Nest and the one the Spitter is on.
     * @return True if the spit was successful, false otherwise.
     */
    public boolean spit(Nest nest) {
        JSONObject args = new JSONObject();
        args.put("nest", Client.getInstance().gameManager.serializeSafe(nest));
        return (boolean)this.runOnServer("spit", args);
    }

    // <<-- Creer-Merge: methods -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    // you can add addtional method(s) here.
    // <<-- /Creer-Merge: methods -->>
}
