/**
 * Generated by Creer at 04:24PM on March 02, 2016 UTC, git hash: '0cc14891fb0c7c6bec65a23a8e2497e80f8827c1'
 * A connection (edge) to a Nest (node) in the game that Spiders can converge on (regardless of owner). Spiders can travel in either direction on Webs.
 */
package games.spiders;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import org.json.JSONObject;
import joueur.Client;
import joueur.BaseGame;
import joueur.BaseGameObject;

// <<-- Creer-Merge: imports -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
// you can add addtional import(s) here
// <<-- /Creer-Merge: imports -->>

/**
 * A connection (edge) to a Nest (node) in the game that Spiders can converge on (regardless of owner). Spiders can travel in either direction on Webs.
 */
public class Web extends GameObject {
    /**
     * How long this Web is, i.e., the distance between its nestA and nestB.
     */
    public float length;

    /**
     * The first Nest this Web is connected to.
     */
    public Nest nestA;

    /**
     * The second Nest this Web is connected to.
     */
    public Nest nestB;

    /**
     * All the Spiderlings currently moving along this Web.
     */
    public List<Spiderling> spiderlings;

    /**
     * How much weight this Web can take before snapping and destroying itself and all the Spiders on it.
     */
    public int strength;


    // <<-- Creer-Merge: fields -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    // you can add addtional field(s) here. None of them will be tracked or updated by the server.
    // <<-- /Creer-Merge: fields -->>


    /**
     * Creates a new instance of a Web. Used during game initialization, do not call directly.
     */
    public Web() {
        super();
        this.spiderlings = new ArrayList<Spiderling>();
    }

    // <<-- Creer-Merge: methods -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    // you can add addtional method(s) here.
    // <<-- /Creer-Merge: methods -->>
}
