/** 
 * Generated by Creer at 02:31PM on October 26, 2015 UTC, git hash: '98604e3773d1933864742cb78acbf6ea0b4ecd7b'
 * A checker on the game board.
 */
package games.checkers;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import org.json.JSONObject;

import joueur.BaseGame;
import joueur.BaseGameObject;
// <<-- Creer-Merge: imports -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
// you can add addtional import(s) here
// <<-- /Creer-Merge: imports -->>
@SuppressWarnings("unused")

/**
 * A checker on the game board.
 */
public class Checker extends GameObject {
    /**
     * If the checker has been kinged and can move backwards.
     */
    public boolean kinged;

    /**
     * The player that controls this Checker.
     */
    public Player owner;

    /**
     * The x coordinate of the checker.
     */
    public int x;

    /**
     * The y coordinate of the checker.
     */
    public int y;


    // <<-- Creer-Merge: fields -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    // you can add addtional field(s) here. None of them will be tracked or updated by the server.
    // <<-- /Creer-Merge: fields -->>


    /**
     * Creates a new instance of Checker. Used during game initialization, do not call directly.
     */
    public Checker() {
        super();
    }

    /**
     * returns if the checker is owned by your player or not
     *
     * @return true if it is yours, false if it is not yours
     */
    public boolean isMine() {
        JSONObject args = new JSONObject();
        return (boolean)this.runOnServer("isMine", args);
    }

    /**
     * Moves the checker from its current location to the given (x, y).
     *
     * @param   x  The x coordinate to move to.
     * @param   y  The y coordinate to move to.
     * @return Returns the same checker that moved if the move was successful. null otherwise.
     */
    public Checker move(int x, int y) {
        JSONObject args = new JSONObject();
        args.put("x", x);
        args.put("y", y);
        return(Checker) this.runOnServer("move", args);
    }

    // <<-- Creer-Merge: methods -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    // you can add addtional method(s) here.
    // <<-- /Creer-Merge: methods -->>
}
