/** 
 * Generated by Creer at 02:31PM on October 26, 2015 UTC, git hash: '98604e3773d1933864742cb78acbf6ea0b4ecd7b'
 * A player in this game. Every AI controls one player.
 */
package games.checkers;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import org.json.JSONObject;

import joueur.BaseGame;
import joueur.BaseGameObject;
// <<-- Creer-Merge: imports -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
// you can add addtional import(s) here
// <<-- /Creer-Merge: imports -->>
@SuppressWarnings("unused")

/**
 * A player in this game. Every AI controls one player.
 */
public class Player extends GameObject {
    /**
     * All the checkers currently in the game owned by this player
     */
    public List<Checker> checkers;

    /**
     * What type of client this is, e.g. 'Python', 'JavaScript', or some other language. For potential data mining purposes.
     */
    public String clientType;

    /**
     * if the player lost the game or not
     */
    public boolean lost;

    /**
     * The name of the player
     */
    public String name;

    /**
     * this player's opponent in the game.
     */
    public Player otherPlayer;

    /**
     * the reason why the player lost the game
     */
    public String reasonLost;

    /**
     * the reason why the player won the game
     */
    public String reasonWon;

    /**
     * The amount of time (in ns) remaining for this AI to send commands.
     */
    public float timeRemaining;

    /**
     * if the player won the game or not
     */
    public boolean won;

    /**
     * The direction your checkers must go along the y-axis until kinged
     */
    public int yDirection;


    // <<-- Creer-Merge: fields -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    // you can add addtional field(s) here. None of them will be tracked or updated by the server.
    // <<-- /Creer-Merge: fields -->>


    /**
     * Creates a new instance of Player. Used during game initialization, do not call directly.
     */
    public Player() {
        super();
        this.checkers = new ArrayList<Checker>();
    }

    // <<-- Creer-Merge: methods -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    // you can add addtional method(s) here.
    // <<-- /Creer-Merge: methods -->>
}
